services:
  - type: web
    name: meme-bot
    runtime: python
    buildCommand: pip install -r requirements.txt --upgrade
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: PORT
        value: 10000